/** PayslipPDF tests — Phase 6 PR6 FE
 *
 * Lightweight smoke test: react-pdf renders to PDF (not React DOM), so we
 * cannot use Testing Library to query rendered output. Instead we verify
 * that:
 *
 *   - The component is a valid React element (no throw at construction)
 *   - The rendered tree is well-formed enough that react-pdf's renderToString()
 *     produces a non-empty PDF when wrapped via the same labels + snapshot
 *     shape PayslipPage passes.
 *
 * We do NOT spin up the heavy pdf() pipeline in unit tests (it pulls in
 * fontkit + brotli + a 5MB worker bundle that slows the suite to a crawl).
 * Asserting `Document` constructs without throwing — given a full
 * PayslipSnapshotPayload + PayslipPDFLabels — is enough to catch the most
 * common breakages (missing prop, wrong field type, null deref).
 */

import { describe, it, expect } from 'vitest'
import { isValidElement } from 'react'
import { PayslipPDF, type PayslipPDFLabels } from '../components/PayslipPDF'
import type { PayslipSnapshotPayload } from '../payroll.types'

const LABELS: PayslipPDFLabels = {
  payslipTitle: 'Payslip',
  periodLabel: 'Period',
  employeeLabel: 'Employee',
  designationLabel: 'Designation',
  phoneLabel: 'Phone',
  presentLabel: 'Present',
  halfLabel: 'Half',
  overtimeMinLabel: 'OT (min)',
  grossLabel: 'Gross',
  advanceLabel: 'Advance',
  deductionsLabel: 'Deductions',
  netLabel: 'Net',
  paymentLabel: 'Payment',
  paymentModeLabel: 'Mode',
  paymentDateLabel: 'Date',
  finalizedByLabel: 'Finalized by',
  footerNote: 'Generated by HisaabPro',
}

function makeSnapshot(
  overrides: Partial<PayslipSnapshotPayload> = {},
): PayslipSnapshotPayload {
  return {
    schemaVersion: 1,
    business: { id: 'biz_1', name: 'Acme Traders', phone: null },
    employee: {
      id: 'emp_1', name: 'Raju Mehta',
      phone: '+919876543210', designation: 'Driver',
      dailyRatePaise: 150000,
    },
    period: { fromDate: '2026-04-01', toDate: '2026-04-30' },
    lines: {
      presentDays: 22, halfDays: 1, overtimeMin: 45,
      basePaise: 3300000, halfPayPaise: 75000, overtimePayPaise: 11250,
      grossPaise: 3386250, advanceTotalPaise: 50000, deductionsPaise: 0,
      netPaise: 3336250,
    },
    payment: { id: 'pay_1', mode: 'CASH', date: '2026-05-01T08:00:00.000Z' },
    finalizedAt: '2026-05-01T08:00:00.000Z',
    finalizedBy: { userId: 'usr_1', name: 'Owner Bhai' },
    ...overrides,
  }
}

describe('<PayslipPDF />', () => {
  it('constructs without throwing on a full snapshot', () => {
    expect(() => PayslipPDF({ snapshot: makeSnapshot(), labels: LABELS })).not.toThrow()
  })

  it('returns a valid React element', () => {
    const tree = PayslipPDF({ snapshot: makeSnapshot(), labels: LABELS })
    expect(isValidElement(tree)).toBe(true)
  })

  it('tolerates null designation + phone (optional employee fields)', () => {
    const snap = makeSnapshot({
      employee: {
        id: 'emp_x', name: 'Volunteer',
        phone: null, designation: null,
        dailyRatePaise: 0,
      },
    })
    expect(() => PayslipPDF({ snapshot: snap, labels: LABELS })).not.toThrow()
  })

  it('tolerates a missing finalizedBy.name (falls back to userId)', () => {
    const snap = makeSnapshot({
      finalizedBy: { userId: 'usr_99', name: null },
    })
    expect(() => PayslipPDF({ snapshot: snap, labels: LABELS })).not.toThrow()
  })

  it('handles a zero-amount payslip without error', () => {
    const snap = makeSnapshot({
      lines: {
        presentDays: 0, halfDays: 0, overtimeMin: 0,
        basePaise: 0, halfPayPaise: 0, overtimePayPaise: 0,
        grossPaise: 0, advanceTotalPaise: 0, deductionsPaise: 0,
        netPaise: 0,
      },
    })
    expect(() => PayslipPDF({ snapshot: snap, labels: LABELS })).not.toThrow()
  })
})
