-- V2 Appointments — Phase 1A
-- Architecture: docs/ARCHITECTURE_V2_APPOINTMENTS.md §2-§3
-- Adapted to HisaabPro: Invoice → Document; BusinessSettings.* lives on Business directly.
--
-- This migration is hand-authored (not generated by `migrate dev`) because the project's
-- shadow DB cannot replay the historical `*_product_trgm_concurrent` migration (CREATE
-- INDEX CONCURRENTLY cannot run inside a transaction). The DDL below was extracted via
-- `prisma migrate diff --from-url=$DATABASE_URL --to-schema-datamodel ... --script` and
-- trimmed to ONLY the v2-appointments-related changes.

-- CreateEnum
CREATE TYPE "AppointmentStatus" AS ENUM ('SCHEDULED', 'CONFIRMED', 'CHECKED_IN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW');

-- CreateEnum
CREATE TYPE "AppointmentRecurrenceFreq" AS ENUM ('DAILY', 'WEEKLY', 'MONTHLY');

-- AlterTable: Business — public-booking HMAC config (architect §2.6; HisaabPro keeps this on Business, not a separate BusinessSettings table)
ALTER TABLE "Business" ADD COLUMN     "publicBookingHmacSecret"    BYTEA,
                       ADD COLUMN     "publicBookingSecretVersion" INTEGER NOT NULL DEFAULT 1;

-- AlterTable: Document — convert-to-invoice back-link (HisaabPro: invoices are Documents with type=SALE_INVOICE)
ALTER TABLE "Document" ADD COLUMN "appointmentId" TEXT;

-- AlterTable: Job — convert-to-job back-link
ALTER TABLE "Job" ADD COLUMN "appointmentId" TEXT;

-- CreateTable: Appointment
CREATE TABLE "Appointment" (
    "id"                   TEXT              NOT NULL,
    "businessId"           TEXT              NOT NULL,
    "partyId"              TEXT,
    "partyNameSnapshot"    TEXT              NOT NULL,
    "employeeId"           TEXT,
    "employeeNameSnapshot" TEXT              NOT NULL,
    "startAt"              TIMESTAMP(3)      NOT NULL,
    "endAt"                TIMESTAMP(3)      NOT NULL,
    "durationMinutes"      INTEGER           NOT NULL,
    "status"               "AppointmentStatus" NOT NULL DEFAULT 'SCHEDULED',
    "notes"                TEXT,
    "serviceId"            TEXT,
    "vertical"             TEXT              NOT NULL,
    "idempotencyKey"       TEXT,
    "createdById"          TEXT              NOT NULL,
    "parentRecurrenceId"   TEXT,
    "createdAt"            TIMESTAMP(3)      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"            TIMESTAMP(3)      NOT NULL,

    CONSTRAINT "Appointment_pkey" PRIMARY KEY ("id")
);

-- CreateTable: AppointmentStatusEvent (audit trail — one row per accepted status transition)
CREATE TABLE "AppointmentStatusEvent" (
    "id"            TEXT              NOT NULL,
    "appointmentId" TEXT              NOT NULL,
    "fromStatus"    "AppointmentStatus",
    "toStatus"      "AppointmentStatus" NOT NULL,
    "reason"        TEXT,
    "actorUserId"   TEXT              NOT NULL,
    "createdAt"     TIMESTAMP(3)      NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AppointmentStatusEvent_pkey" PRIMARY KEY ("id")
);

-- CreateTable: AppointmentRecurrenceTemplate
CREATE TABLE "AppointmentRecurrenceTemplate" (
    "id"          TEXT                       NOT NULL,
    "businessId"  TEXT                       NOT NULL,
    "frequency"   "AppointmentRecurrenceFreq" NOT NULL,
    "startAt"     TIMESTAMP(3)               NOT NULL,
    "endAt"       TIMESTAMP(3)               NOT NULL,
    "occurrences" INTEGER                    NOT NULL,
    "createdAt"   TIMESTAMP(3)               NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AppointmentRecurrenceTemplate_pkey" PRIMARY KEY ("id")
);

-- CreateTable: AppointmentWaitlist
CREATE TABLE "AppointmentWaitlist" (
    "id"                    TEXT         NOT NULL,
    "businessId"            TEXT         NOT NULL,
    "partyId"               TEXT         NOT NULL,
    "employeeId"            TEXT,
    "preferredDate"         TIMESTAMP(3) NOT NULL,
    "notes"                 TEXT,
    "promotedAppointmentId" TEXT,
    "createdAt"             TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AppointmentWaitlist_pkey" PRIMARY KEY ("id")
);

-- CreateIndex: Document/Job back-link covering indexes
CREATE INDEX "Document_appointmentId_idx" ON "Document"("appointmentId");
CREATE INDEX "Job_appointmentId_idx"      ON "Job"("appointmentId");

-- CreateIndex: Appointment hot paths
CREATE UNIQUE INDEX "Appointment_idempotencyKey_key"                ON "Appointment"("idempotencyKey");
CREATE INDEX        "Appointment_businessId_startAt_idx"            ON "Appointment"("businessId", "startAt");
CREATE INDEX        "Appointment_businessId_employeeId_startAt_idx" ON "Appointment"("businessId", "employeeId", "startAt");
CREATE INDEX        "Appointment_partyId_startAt_idx"               ON "Appointment"("partyId", "startAt");
CREATE INDEX        "Appointment_businessId_status_startAt_idx"     ON "Appointment"("businessId", "status", "startAt");
CREATE INDEX        "Appointment_parentRecurrenceId_idx"            ON "Appointment"("parentRecurrenceId");

-- CreateIndex: AppointmentStatusEvent
CREATE INDEX "AppointmentStatusEvent_appointmentId_createdAt_idx" ON "AppointmentStatusEvent"("appointmentId", "createdAt");

-- CreateIndex: AppointmentRecurrenceTemplate
CREATE INDEX "AppointmentRecurrenceTemplate_businessId_idx" ON "AppointmentRecurrenceTemplate"("businessId");

-- CreateIndex: AppointmentWaitlist
CREATE UNIQUE INDEX "AppointmentWaitlist_promotedAppointmentId_key" ON "AppointmentWaitlist"("promotedAppointmentId");
CREATE INDEX        "AppointmentWaitlist_businessId_preferredDate_idx" ON "AppointmentWaitlist"("businessId", "preferredDate");
CREATE INDEX        "AppointmentWaitlist_partyId_idx"                  ON "AppointmentWaitlist"("partyId");

-- AddForeignKey: Document.appointmentId → Appointment(id) ON DELETE SET NULL (convert flow idempotency)
ALTER TABLE "Document" ADD CONSTRAINT "Document_appointmentId_fkey" FOREIGN KEY ("appointmentId") REFERENCES "Appointment"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey: Job.appointmentId → Appointment(id) ON DELETE SET NULL
ALTER TABLE "Job" ADD CONSTRAINT "Job_appointmentId_fkey" FOREIGN KEY ("appointmentId") REFERENCES "Appointment"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey: Appointment relations
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_businessId_fkey"         FOREIGN KEY ("businessId")         REFERENCES "Business"("id")                      ON DELETE RESTRICT ON UPDATE CASCADE;
-- partyId/employeeId are SET NULL (not Restrict) — restriction lives in app guard per §2.7
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_partyId_fkey"            FOREIGN KEY ("partyId")            REFERENCES "Party"("id")                         ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_employeeId_fkey"         FOREIGN KEY ("employeeId")         REFERENCES "Employee"("id")                      ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_createdById_fkey"        FOREIGN KEY ("createdById")        REFERENCES "User"("id")                          ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_parentRecurrenceId_fkey" FOREIGN KEY ("parentRecurrenceId") REFERENCES "AppointmentRecurrenceTemplate"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey: AppointmentStatusEvent relations
ALTER TABLE "AppointmentStatusEvent" ADD CONSTRAINT "AppointmentStatusEvent_appointmentId_fkey" FOREIGN KEY ("appointmentId") REFERENCES "Appointment"("id") ON DELETE CASCADE  ON UPDATE CASCADE;
ALTER TABLE "AppointmentStatusEvent" ADD CONSTRAINT "AppointmentStatusEvent_actorUserId_fkey"   FOREIGN KEY ("actorUserId")   REFERENCES "User"("id")        ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey: AppointmentRecurrenceTemplate relations
ALTER TABLE "AppointmentRecurrenceTemplate" ADD CONSTRAINT "AppointmentRecurrenceTemplate_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey: AppointmentWaitlist relations
ALTER TABLE "AppointmentWaitlist" ADD CONSTRAINT "AppointmentWaitlist_businessId_fkey"            FOREIGN KEY ("businessId")            REFERENCES "Business"("id")    ON DELETE CASCADE  ON UPDATE CASCADE;
ALTER TABLE "AppointmentWaitlist" ADD CONSTRAINT "AppointmentWaitlist_partyId_fkey"               FOREIGN KEY ("partyId")               REFERENCES "Party"("id")       ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AppointmentWaitlist" ADD CONSTRAINT "AppointmentWaitlist_employeeId_fkey"            FOREIGN KEY ("employeeId")            REFERENCES "Employee"("id")    ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AppointmentWaitlist" ADD CONSTRAINT "AppointmentWaitlist_promotedAppointmentId_fkey" FOREIGN KEY ("promotedAppointmentId") REFERENCES "Appointment"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ─────────────────────────────────────────────────────────────────────────────
-- Raw-SQL additions (NOT expressible in Prisma DSL — appended per architect §3)
-- ─────────────────────────────────────────────────────────────────────────────

-- 1) btree_gist — required for the EXCLUDE constraint below to mix `=` (employeeId) with `&&` (tstzrange)
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- 2) Exclusion constraint: a single employee cannot have two ACTIVE appointments
--    whose [startAt, endAt) ranges overlap. NULL employeeId rows are skipped
--    naturally (gist `=` is NULL-excluding); the WHERE clause restricts to
--    statuses where overlap is meaningful (terminal statuses can overlap freely).
--
--    NOTE: tsrange (NOT tstzrange) because Prisma's DateTime maps to
--    `TIMESTAMP(3) WITHOUT TIME ZONE`. `tstzrange(timestamp, timestamp, text)`
--    is STABLE-not-IMMUTABLE on a tz-less input column, which the gist index
--    expression rejects. Server layer must always pass UTC to startAt/endAt.
ALTER TABLE "Appointment" ADD CONSTRAINT appointment_no_overlap
  EXCLUDE USING gist (
    "employeeId" WITH =,
    tsrange("startAt", "endAt", '[)') WITH &&
  ) WHERE ("status" IN ('SCHEDULED', 'CONFIRMED', 'CHECKED_IN'));

-- 3) Denormalized-column consistency: endAt must equal startAt + durationMinutes.
--    Service layer always computes endAt; this CHECK guards against admin/ops
--    scripts or accidental client-supplied values.
ALTER TABLE "Appointment" ADD CONSTRAINT appointment_endat_consistent
  CHECK ("endAt" = "startAt" + ("durationMinutes" || ' minutes')::interval);

-- 4) Partial index for the hot day/week list view, restricted to ACTIVE statuses.
--    Backs `GET /appointments?from=&to=&status=active` and the calendar grid.
CREATE INDEX appointment_business_start_active_idx
  ON "Appointment" ("businessId", "startAt")
  WHERE "status" IN ('SCHEDULED', 'CONFIRMED', 'CHECKED_IN');
