/**
 * A planted B2 violation, shared by A9 (the pre-commit hook) and A9b (the CI
 * step). Both assertions need the same thing: a file that the raw-client lint
 * MUST reject, written somewhere the lint actually looks.
 *
 * `server/src/services/` is deliberate. `lint-raw-client.mjs` skips any
 * directory named `__tests__` (IGNORED_DIRS), so a probe written next to these
 * tests would be invisible to the lint and both assertions would pass while
 * proving nothing — the exact vacuous-green shape §12 exists to prevent.
 *
 * The identifier is assembled at runtime rather than written literally so this
 * helper is not itself a violation of the rule it plants.
 */
import { rmSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

export const REPO_ROOT = resolve(__dirname, '../../../..')

/** Named for what it is, so a leaked copy is obviously debris and not a real service. */
export const PROBE_REL = 'server/src/services/__adoption_leak_probe.generated.ts'
export const PROBE_ABS = resolve(REPO_ROOT, PROBE_REL)

const RAW_CLIENT = ['__base', 'Prisma', 'Unsafe'].join('')

/**
 * Write the probe. Callers MUST pair this with {@link removeLeakProbe} in a
 * `finally`/`afterEach` — a probe left behind fails the repo's own pre-commit
 * hook for whoever commits next, which would be this test breaking the gate it
 * is meant to verify.
 */
export function plantLeakProbe(): void {
  writeFileSync(
    PROBE_ABS,
    `// Generated by an adoption test. If you are reading this in a diff, a test\n` +
      `// crashed before cleanup — delete this file.\n` +
      `import { ${RAW_CLIENT} } from '../lib/prisma.js'\n` +
      `export const leak = () => ${RAW_CLIENT}.party.findMany()\n`,
    'utf8',
  )
}

export function removeLeakProbe(): void {
  rmSync(PROBE_ABS, { force: true })
}
