/**
 * E-Way Bill error codes.
 * Shared: sanitizeNicError, maskGstin imported from einvoice.errors (no duplication).
 */

export { sanitizeNicError, maskGstin } from '../einvoice/einvoice.errors.js'

export const EWAYBILL_ERRORS = {
  BELOW_THRESHOLD: 'EWAYBILL_BELOW_THRESHOLD',
  NOT_INTERSTATE: 'EWAYBILL_NOT_INTERSTATE',
  CANCEL_WINDOW_EXPIRED: 'EWAYBILL_CANCEL_WINDOW_EXPIRED',
  PART_B_REQUIRED: 'EWAYBILL_PART_B_REQUIRED',
  ALREADY_GENERATED: 'EWAYBILL_ALREADY_GENERATED',
  ALREADY_CANCELLED: 'EWAYBILL_ALREADY_CANCELLED',
  NOT_FOUND: 'EWAYBILL_NOT_FOUND',
  NIC_AUTH_FAILED: 'EWAYBILL_NIC_AUTH_FAILED',
  NIC_CIRCUIT_OPEN: 'EWAYBILL_NIC_CIRCUIT_OPEN',
  NIC_TIMEOUT: 'EWAYBILL_NIC_TIMEOUT',
  NIC_NOT_CONFIGURED: 'NIC_EWB_NOT_CONFIGURED',
  QUOTA_EXCEEDED: 'EWAYBILL_QUOTA_EXCEEDED',
} as const

export type EWayBillErrorCode = (typeof EWAYBILL_ERRORS)[keyof typeof EWAYBILL_ERRORS]
