/** Route paths — single source of truth */

export const ROUTES = {
  HOME: '/',
  PRICING: '/pricing',
  LOGIN: '/login',
  REGISTER: '/register',
  VERIFY_OTP: '/verify-otp',
  FORGOT_PASSWORD: '/forgot-password',
  ONBOARDING: '/onboarding',
  DASHBOARD: '/dashboard',
  MORE: '/more',
  PARTIES: '/parties',
  PARTY_NEW: '/parties/new',
  PARTY_DETAIL: '/parties/:id',
  PARTY_EDIT: '/parties/:id/edit',
  // Epic D #127 — CRM follow-up queue (linked from Parties + Detail CRM tab).
  CRM_FOLLOWUPS: '/crm/follow-ups',
  PRODUCTS: '/products',
  PRODUCT_NEW: '/products/new',
  PRODUCT_DETAIL: '/products/:id',
  PRODUCT_EDIT: '/products/:id/edit',
  INVOICES: '/invoices',
  INVOICE_CREATE: '/invoices/new',
  INVOICE_DETAIL: '/invoices/:id',
  INVOICE_EDIT: '/invoices/:id/edit',
  PAYMENTS: '/payments',
  PAYMENT_NEW: '/payments/new',
  PAYMENT_DETAIL: '/payments/:id',
  PAYMENT_EDIT: '/payments/:id/edit',
  OUTSTANDING: '/outstanding',
  REPORTS: '/reports',
  REPORT_SALES: '/reports/sales',
  REPORT_PURCHASES: '/reports/purchases',
  REPORT_PARTY_STATEMENT: '/reports/party-statement/:partyId',
  REPORT_STOCK_SUMMARY: '/reports/stock-summary',
  REPORT_DAY_BOOK: '/reports/day-book',
  REPORT_PAYMENT_HISTORY: '/reports/payment-history',
  SETTINGS: '/settings',
  SETTINGS_ROLES: '/settings/roles',
  SETTINGS_ROLE_NEW: '/settings/roles/new',
  SETTINGS_ROLE_EDIT: '/settings/roles/:id',
  SETTINGS_STAFF: '/settings/staff',
  SETTINGS_STAFF_INVITE: '/settings/staff/invite',
  SETTINGS_SECURITY: '/settings/security',
  SETTINGS_TRANSACTION_CONTROLS: '/settings/transaction-controls',
  SETTINGS_DOCUMENTS: '/settings/documents',
  SETTINGS_DOC_CUSTOM_FIELDS: '/settings/document-custom-fields',
  SETTINGS_AUDIT_LOG: '/settings/audit-log',
  SETTINGS_SHORTCUTS: '/settings/shortcuts',
  SETTINGS_PIN_SETUP: '/settings/pin-setup',
  SETTINGS_SUBSCRIPTION: '/settings/subscription',
  SETTINGS_SUBSCRIPTION_CHECKOUT: '/settings/subscription/checkout',
  SETTINGS_GST: '/settings/gst',
  SETTINGS_TAX_RATES: '/settings/tax-rates',
  SETTINGS_TAX_RATE_NEW: '/settings/tax-rates/new',
  SETTINGS_TAX_RATE_EDIT: '/settings/tax-rates/:id',
  REPORT_GST_RETURNS: '/reports/gst-returns',
  REPORT_TAX_SUMMARY: '/reports/tax-summary',
  REPORT_TDS_TCS: '/reports/tds-tcs',
  TEMPLATES: '/settings/templates',
  TEMPLATE_EDIT: '/settings/templates/:id',
  SETTINGS_CURRENCY: '/settings/currency',
  RECURRING: '/recurring',
  RECURRING_DETAIL: '/recurring/:id',
  RECURRING_NEW: '/recurring/new',
  RECURRING_EDIT: '/recurring/:id/edit',
  GST_RECONCILIATION: '/gst/reconciliation',
  GST_RECONCILIATION_DETAIL: '/gst/reconciliation/:id',
  CHART_OF_ACCOUNTS: '/accounting/chart-of-accounts',
  JOURNAL_ENTRIES: '/accounting/journal-entries',
  TRIAL_BALANCE: '/reports/trial-balance',
  BANK_ACCOUNTS: '/bank-accounts',
  EXPENSES: '/expenses',
  OTHER_INCOME: '/other-income',
  CHEQUES: '/cheques',
  LOANS: '/loans',
  LOAN_DETAIL: '/loans/:id',
  REPORT_PROFIT_LOSS: '/reports/profit-loss',
  REPORT_BALANCE_SHEET: '/reports/balance-sheet',
  REPORT_CASH_FLOW: '/reports/cash-flow',
  REPORT_AGING: '/reports/aging',
  REPORT_PROFITABILITY: '/reports/profitability',
  REPORT_DISCOUNTS: '/reports/discounts',
  INSIGHTS: '/insights',
  REORDER_SUGGESTIONS: '/inventory/reorder-suggestions',
  FY_CLOSURE: '/accounting/fy-closure',
  TALLY_EXPORT: '/accounting/tally-export',
  BILL_SCAN: '/bill-scan',
  BULK_IMPORT_PARTIES: '/parties/import',
  IMPORTS: '/imports',
  IMPORT_JOB_DETAIL: '/imports/:jobId',
  PUBLIC_LEDGER: '/public/ledger/:token',
  ITEMS_LIBRARY: '/products/library',
  DATA_IMPORT: '/settings/import',
  SMART_GREETINGS: '/greetings',
  MARKETING_HUB: '/marketing',
  MARKETING_TEMPLATES: '/marketing/templates',
  MARKETING_TEMPLATE_NEW: '/marketing/templates/new',
  MARKETING_TEMPLATE_EDIT: '/marketing/templates/:id',
  MARKETING_CAMPAIGNS: '/marketing/campaigns',
  MARKETING_CAMPAIGN_NEW: '/marketing/campaigns/new',
  MARKETING_CAMPAIGN_DETAIL: '/marketing/campaigns/:id',
  MARKETING_REMINDERS: '/marketing/reminders',
  MARKETING_REMINDER_NEW: '/marketing/reminders/new',
  MARKETING_REMINDER_EDIT: '/marketing/reminders/:id',
  MARKETING_OPT_OUTS: '/marketing/opt-outs',
  SETTINGS_UNITS: '/settings/units',
  SETTINGS_PERMISSIONS: '/settings/permissions',
  SETTINGS_INVENTORY: '/settings/inventory',
  SETTINGS_LOYALTY: '/settings/loyalty',
  // Epic D #128 — Commission rules + ledger + leaderboard
  SETTINGS_COMMISSION: '/settings/commission',
  COMMISSION_LEDGER: '/commission/ledger',
  COMMISSION_LEADERBOARD: '/commission/leaderboard',
  JOIN_BUSINESS: '/join',
  CREATE_BUSINESS: '/business/create',
  BUSINESS_TYPE: '/business/type',
  ADMIN_COUPONS: '/admin/coupons',
  ADMIN_COUPON_DETAIL: '/admin/coupons/:id',

  // Phase 4 — Advanced Inventory
  BATCHES: '/products/:productId/batches',
  BATCH_NEW: '/products/:productId/batches/new',
  BATCH_DETAIL: '/batches/:id',
  GODOWNS: '/godowns',
  GODOWN_NEW: '/godowns/new',
  GODOWN_DETAIL: '/godowns/:id',
  GODOWN_EDIT: '/godowns/:id/edit',
  GODOWN_TRANSFER: '/godowns/transfer',
  STOCK_VERIFICATION: '/stock-verification',
  STOCK_VERIFICATION_DETAIL: '/stock-verification/:id',
  SERIAL_NUMBERS: '/products/:productId/serials',
  SERIAL_NEW: '/products/:productId/serials/new',
  SERIAL_BULK: '/products/:productId/serials/bulk',
  SERIAL_LOOKUP: '/serial-lookup',

  // Phase 3 — Jobs (services vertical)
  JOBS:       '/jobs',
  JOB_NEW:    '/jobs/new',
  JOB_DETAIL: '/jobs/:id',
  JOB_EDIT:   '/jobs/:id/edit',

  // Phase 5 Epic B — Sales Pipeline (#122)
  SALES:                  '/sales',
  ESTIMATES:              '/sales/estimates',
  ESTIMATE_NEW:           '/sales/estimates/new',
  ESTIMATE_DETAIL:        '/sales/estimates/:id',
  ESTIMATE_EDIT:          '/sales/estimates/:id/edit',
  SALE_ORDERS:            '/sales/orders',
  SALE_ORDER_NEW:         '/sales/orders/new',
  SALE_ORDER_DETAIL:      '/sales/orders/:id',
  SALE_ORDER_EDIT:        '/sales/orders/:id/edit',
  DELIVERY_CHALLANS:      '/sales/challans',
  DELIVERY_CHALLAN_NEW:   '/sales/challans/new',
  DELIVERY_CHALLAN_DETAIL:'/sales/challans/:id',
  DELIVERY_CHALLAN_EDIT:  '/sales/challans/:id/edit',

  // Phase 4 — Custom Orders (bakery / tailor vertical)
  ORDERS:       '/orders',
  ORDER_NEW:    '/orders/new',
  ORDER_DETAIL: '/orders/:id',
  ORDER_EDIT:   '/orders/:id/edit',

  // POS
  POS:             '/pos',
  POS_HISTORY:     '/pos/history',
  POS_SALE_DETAIL: '/pos/sales/:id',

  // Account
  SETTINGS_SESSIONS: '/settings/sessions',

  // GST Phase 2 — Backfill Wizard
  GST_BACKFILL: '/gst/backfill',

  // GST Phase 2 — GSTR-1 Export (PR 10)
  GST_GSTR1: '/gst/returns/gstr1',

  // GST Phase 2 — GSTR-3B Summary (PR 11)
  GST_GSTR3B: '/gst/returns/gstr3b',

  // Payments Hub — Collections (PR 3)
  COLLECTIONS: '/collections',
  COLLECTIONS_BUCKET: '/collections/bucket/:bucket',

  // Inventory Phase 2 — Purchase + Alerts
  INVENTORY_ALERTS: '/inventory/alerts',
  PURCHASES: '/purchases',
  PURCHASE_DETAIL: '/purchases/:id',
  PURCHASE_NEW: '/purchases/new',
  PURCHASE_EDIT: '/purchases/:id/edit',

  // Inventory Phase 2 — Stock Verification mobile flow (INV-07)
  INVENTORY_VERIFY: '/inventory/verify',
  INVENTORY_VERIFY_RUN: '/inventory/verify/:id',

  // Inventory Phase 2 — Stock value report (INV-07)
  STOCK_VALUE_REPORT: '/reports/stock-value',

  // Cash Register (PR 4)
  CASH_REGISTER: '/cash-register',

  // Notifications Engine (PR12+PR13)
  NOTIFICATIONS:              '/notifications',
  NOTIFICATION_PREFERENCES:   '/notifications/preferences',

  // #132 — Price Lists (Batch 4)
  PRICE_LISTS:       '/settings/price-lists',
  PRICE_LIST_DETAIL: '/settings/price-lists/:id',

  // Epic C PR4 — Online Storefront (#121)
  STOREFRONT_SETTINGS: '/settings/storefront',

  // Phase 4 — BOM / Manufacturing (PR4-PR6)
  BOM:              '/bom',
  BOM_NEW:          '/bom/new',
  BOM_DETAIL:       '/bom/:id',
  BOM_EDIT:         '/bom/:id/edit',
  PRODUCTION_RUNS:  '/production-runs',
  PRODUCTION_RUN_NEW:    '/production-runs/new',
  PRODUCTION_RUN_DETAIL: '/production-runs/:id',

  // Phase 6 — Staff & HR (PR5 ships Attendance; PR6 ships Employees + Payroll)
  HR_ATTENDANCE:       '/hr/attendance',
  HR_EMPLOYEES:        '/hr/employees',
  HR_EMPLOYEE_DETAIL:  '/hr/employees/:id',
  HR_PAYROLL:          '/hr/payroll',
  HR_PAYROLL_NEW:      '/hr/payroll/new',
  HR_PAYROLL_DETAIL:   '/hr/payroll/:id',
  PAYSLIP:             '/hr/payroll/:runId/payslip/:payrollId',
} as const
