/** Route paths — single source of truth */

export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  ONBOARDING: '/onboarding',
  DASHBOARD: '/dashboard',
  PARTIES: '/parties',
  PARTY_NEW: '/parties/new',
  PARTY_DETAIL: '/parties/:id',
  PRODUCTS: '/products',
  PRODUCT_NEW: '/products/new',
  PRODUCT_DETAIL: '/products/:id',
  INVOICES: '/invoices',
  INVOICE_CREATE: '/invoices/new',
  INVOICE_DETAIL: '/invoices/:id',
  PAYMENTS: '/payments',
  PAYMENT_NEW: '/payments/new',
  PAYMENT_DETAIL: '/payments/:id',
  OUTSTANDING: '/outstanding',
  REPORTS: '/reports',
  REPORT_SALES: '/reports/sales',
  REPORT_PURCHASES: '/reports/purchases',
  REPORT_PARTY_STATEMENT: '/reports/party-statement/:partyId',
  REPORT_STOCK_SUMMARY: '/reports/stock-summary',
  REPORT_DAY_BOOK: '/reports/day-book',
  REPORT_PAYMENT_HISTORY: '/reports/payment-history',
  SETTINGS: '/settings',
  SETTINGS_ROLES: '/settings/roles',
  SETTINGS_ROLE_NEW: '/settings/roles/new',
  SETTINGS_ROLE_EDIT: '/settings/roles/:id',
  SETTINGS_STAFF: '/settings/staff',
  SETTINGS_STAFF_INVITE: '/settings/staff/invite',
  SETTINGS_SECURITY: '/settings/security',
  SETTINGS_TRANSACTION_CONTROLS: '/settings/transaction-controls',
  SETTINGS_AUDIT_LOG: '/settings/audit-log',
  SETTINGS_SHORTCUTS: '/settings/shortcuts',
  SETTINGS_PIN_SETUP: '/settings/pin-setup',
  TEMPLATES: '/settings/templates',
  TEMPLATE_EDIT: '/settings/templates/:id',
} as const
