/** Lazy-loaded page imports — split per route for small bundles */

import { lazy } from 'react'

export const CalculatorOverlay = lazy(() =>
  import('@/features/settings/CalculatorOverlay').then((m) => ({ default: m.CalculatorOverlay }))
)
export const FeedbackWidget = lazy(() =>
  import('@/components/feedback/FeedbackWidget').then((m) => ({ default: m.FeedbackWidget }))
)

export const Login = lazy(() => import('@/features/auth/LoginPage'))
export const Register = lazy(() => import('@/features/auth/RegisterPage'))
export const VerifyOtp = lazy(() => import('@/features/auth/VerifyOtpPage'))
export const ForgotPassword = lazy(() => import('@/features/auth/ForgotPasswordPage'))
export const Onboarding = lazy(() => import('@/features/onboarding/OnboardingPage'))
export const Dashboard = lazy(() => import('@/features/dashboard/DashboardPage'))
export const DashboardPreview = lazy(() => import('@/features/dashboard-preview/DashboardPreviewPage'))
export const Parties = lazy(() => import('@/features/parties/PartiesPage'))
export const CreateParty = lazy(() => import('@/features/parties/CreatePartyPage'))
export const PartyDetail = lazy(() => import('@/features/parties/PartyDetailPage'))
export const Products = lazy(() => import('@/features/products/ProductsPage'))
export const CreateProduct = lazy(() => import('@/features/products/CreateProductPage'))
export const Categories = lazy(() => import('@/features/products/CategoriesPage'))
export const StockAdjustments = lazy(() => import('@/features/products/StockAdjustmentsPage'))
export const ExpenseCategories = lazy(() => import('@/features/expenses/pages/ExpenseCategoriesPage'))
export const ProductDetail = lazy(() => import('@/features/products/ProductDetailPage'))
export const Invoices = lazy(() => import('@/features/invoices/InvoicesPage'))
export const DraftInvoices = lazy(() => import('@/features/invoices/DraftInvoicesPage'))
export const CreateInvoice = lazy(() => import('@/features/invoices/CreateInvoicePage'))
export const InvoiceDetail = lazy(() => import('@/features/invoices/InvoiceDetailPage'))
export const EditParty = lazy(() => import('@/features/parties/EditPartyPage'))
export const EditProduct = lazy(() => import('@/features/products/EditProductPage'))
export const EditInvoice = lazy(() => import('@/features/invoices/EditInvoicePage'))
export const TemplateGallery = lazy(() => import('@/features/templates/TemplateGalleryPage'))
export const TemplateEditor = lazy(() => import('@/features/templates/TemplateEditorPage'))
export const Payments = lazy(() => import('@/features/payments/PaymentsPage'))
export const RecordPayment = lazy(() => import('@/features/payments/RecordPaymentPage'))
export const PaymentDetail = lazy(() => import('@/features/payments/PaymentDetailPage'))
export const EditPayment = lazy(() => import('@/features/payments/EditPaymentPage'))
export const Outstanding = lazy(() => import('@/features/payments/OutstandingPage'))
export const ReportsHub = lazy(() => import('@/features/reports/ReportsHubPage'))
export const SaleReport = lazy(() => import('@/features/reports/InvoiceReportPage'))
export const PurchaseReport = lazy(() => import('@/features/reports/InvoiceReportPage'))
export const PartyStatement = lazy(() => import('@/features/reports/PartyStatementPage'))
export const StockSummary = lazy(() => import('@/features/reports/StockSummaryPage'))
export const DayBook = lazy(() => import('@/features/reports/DayBookPage'))
export const PaymentHistory = lazy(() => import('@/features/reports/PaymentHistoryPage'))
export const TaxSummary = lazy(() => import('@/features/reports/TaxSummaryPage'))
export const GstReturns = lazy(() => import('@/features/reports/GstReturnsPage'))
export const TdsTcsReport = lazy(() => import('@/features/reports/TdsTcsReportPage'))
export const Settings = lazy(() => import('@/features/settings/SettingsPage'))
export const SubscriptionManage = lazy(() => import('@/pages/SubscriptionManagePage'))
export const SubscriptionCheckout = lazy(() => import('@/features/subscription-checkout/SubscriptionCheckoutPage'))
export const Roles = lazy(() => import('@/features/settings/RolesPage'))
export const RoleBuilder = lazy(() => import('@/features/settings/RoleBuilderPage'))
export const Staff = lazy(() => import('@/features/settings/StaffPage'))
export const StaffInvite = lazy(() => import('@/features/settings/StaffInvitePage'))
export const TransactionControls = lazy(() => import('@/features/settings/TransactionControlsPage'))
export const AuditLog = lazy(() => import('@/features/settings/AuditLogPage'))
export const ActiveSessions = lazy(() => import('@/features/settings/ActiveSessionsPage'))
export const PinSetup = lazy(() => import('@/features/settings/PinSetupPage'))
export const Shortcuts = lazy(() => import('@/features/settings/ShortcutsPage'))
export const ThemeAppearance = lazy(() => import('@/features/settings/ThemeAppearancePage'))
export const BackupSettings = lazy(() => import('@/features/backup/BackupPage'))
export const GstSettings = lazy(() => import('@/features/gst/GstSettingsPage'))
export const TaxCategories = lazy(() => import('@/features/tax/TaxCategoriesPage'))
export const CreateTaxCategory = lazy(() => import('@/features/tax/CreateTaxCategoryPage'))
export const EditTaxCategory = lazy(() => import('@/features/tax/EditTaxCategoryPage'))
export const CurrencySettings = lazy(() => import('@/features/settings/currency/CurrencySettingsPage'))
export const RecurringList = lazy(() => import('@/features/recurring/pages/RecurringListPage'))
export const RecurringDetail = lazy(() => import('@/features/recurring/pages/RecurringDetailPage'))
export const RecurringForm = lazy(() => import('@/features/recurring/pages/RecurringFormPage'))
export const GstReconciliationList = lazy(() => import('@/features/gst-reconciliation/ReconciliationListPage'))
export const GstReconciliationDetail = lazy(() => import('@/features/gst-reconciliation/ReconciliationDetailPage'))
export const ChartOfAccounts = lazy(() => import('@/features/accounting/ChartOfAccountsPage'))
export const JournalEntries = lazy(() => import('@/features/accounting/JournalEntriesPage'))
export const TrialBalance = lazy(() => import('@/features/accounting/TrialBalancePage'))
export const BankAccounts = lazy(() => import('@/features/bank-accounts/BankAccountsPage'))
export const Expenses = lazy(() => import('@/features/expenses/ExpensesPage'))
export const ExpensesPending = lazy(() => import('@/features/expenses/pages/PendingExpensesPage'))
export const ExpensesBudgets = lazy(() => import('@/features/expenses/pages/BudgetsPage'))
export const ExpensesRecurring = lazy(() => import('@/features/expenses/pages/RecurringPage'))
export const ExpenseDetail = lazy(() => import('@/features/expenses/pages/ExpenseDetailPage'))
export const OtherIncome = lazy(() => import('@/features/other-income/OtherIncomePage'))
export const Cheques = lazy(() => import('@/features/cheques/ChequesPage'))
export const Loans = lazy(() => import('@/features/loans/LoansPage'))
export const LoanDetail = lazy(() => import('@/features/loans/LoanDetailPage'))
export const ProfitLoss = lazy(() => import('@/features/reports/ProfitLossPage'))
export const BalanceSheet = lazy(() => import('@/features/reports/BalanceSheetPage'))
export const CashFlow = lazy(() => import('@/features/reports/CashFlowPage'))
export const AgingReport = lazy(() => import('@/features/reports/AgingReportPage'))
export const ProfitabilityReport = lazy(() => import('@/features/reports/ProfitabilityReportPage'))
export const DiscountReport = lazy(() => import('@/features/reports/DiscountReportPage'))
export const PredictiveAnalytics = lazy(() => import('@/features/analytics/PredictiveAnalyticsPage'))
export const ReorderSuggestions = lazy(() => import('@/features/reorder/ReorderSuggestionsPage'))
export const GstFilingReadiness = lazy(() => import('@/features/gst-validation/GstFilingReadinessPage'))
export const VoiceEntry = lazy(() => import('@/features/voice/VoiceEntryPage'))
export const BankReconciliation = lazy(() => import('@/features/bank-reconciliation/BankReconciliationPage'))
export const TallyExport = lazy(() => import('@/features/reports/TallyExportPage'))
export const FYClosure = lazy(() => import('@/features/accounting/FYClosurePage'))
export const More = lazy(() => import('@/features/more/MorePage'))
export const BillScan = lazy(() => import('@/features/bill-scan/BillScanPage'))
export const BulkImport = lazy(() => import('@/features/bulk-import/BulkImportPage'))
export const PublicLedger = lazy(() => import('@/features/shared-ledger/PublicLedgerPage'))
export const ItemsLibrary = lazy(() => import('@/features/items-library/ItemsLibraryPage'))
export const ImportUpload = lazy(() => import('@/features/import/pages/ImportUpload'))
export const ImportJobStub = lazy(() => import('@/features/import/pages/ImportJobPage'))
export const SmartGreetings = lazy(() => import('@/features/smart-greetings/SmartGreetingsPage'))
export const Units = lazy(() => import('@/features/units/UnitsPage'))
export const JoinBusiness = lazy(() => import('@/features/business/JoinBusinessPage'))
export const CreateBusiness = lazy(() => import('@/features/business/CreateBusinessPage'))
export const BusinessType = lazy(() => import('@/features/business/BusinessTypePage'))
export const Landing = lazy(() => import('@/features/landing/LandingPage'))
export const AdminCoupons = lazy(() => import('@/features/admin/coupons/CouponsPage'))
export const AdminCouponDetail = lazy(() => import('@/features/admin/coupons/CouponDetailPage'))

// Later-phase pages live in a sibling barrel to keep each file under the
// 250-line limit; consumers still import everything from '@/app.routes'.
export * from './app.routes.advanced'
