/** Lazy-loaded page imports — split per route for small bundles */

import { lazy } from 'react'

export const CalculatorOverlay = lazy(() =>
  import('@/features/settings/CalculatorOverlay').then((m) => ({ default: m.CalculatorOverlay }))
)
export const FeedbackWidget = lazy(() =>
  import('@/components/feedback/FeedbackWidget').then((m) => ({ default: m.FeedbackWidget }))
)

export const Login = lazy(() => import('@/features/auth/LoginPage'))
export const Register = lazy(() => import('@/features/auth/RegisterPage'))
export const VerifyOtp = lazy(() => import('@/features/auth/VerifyOtpPage'))
export const Onboarding = lazy(() => import('@/features/onboarding/OnboardingPage'))
export const Dashboard = lazy(() => import('@/features/dashboard/DashboardPage'))
export const Parties = lazy(() => import('@/features/parties/PartiesPage'))
export const CreateParty = lazy(() => import('@/features/parties/CreatePartyPage'))
export const PartyDetail = lazy(() => import('@/features/parties/PartyDetailPage'))
export const Products = lazy(() => import('@/features/products/ProductsPage'))
export const CreateProduct = lazy(() => import('@/features/products/CreateProductPage'))
export const ProductDetail = lazy(() => import('@/features/products/ProductDetailPage'))
export const Invoices = lazy(() => import('@/features/invoices/InvoicesPage'))
export const CreateInvoice = lazy(() => import('@/features/invoices/CreateInvoicePage'))
export const InvoiceDetail = lazy(() => import('@/features/invoices/InvoiceDetailPage'))
export const EditParty = lazy(() => import('@/features/parties/EditPartyPage'))
export const EditProduct = lazy(() => import('@/features/products/EditProductPage'))
export const EditInvoice = lazy(() => import('@/features/invoices/EditInvoicePage'))
export const TemplateGallery = lazy(() => import('@/features/templates/TemplateGalleryPage'))
export const TemplateEditor = lazy(() => import('@/features/templates/TemplateEditorPage'))
export const Payments = lazy(() => import('@/features/payments/PaymentsPage'))
export const RecordPayment = lazy(() => import('@/features/payments/RecordPaymentPage'))
export const PaymentDetail = lazy(() => import('@/features/payments/PaymentDetailPage'))
export const EditPayment = lazy(() => import('@/features/payments/EditPaymentPage'))
export const Outstanding = lazy(() => import('@/features/payments/OutstandingPage'))
export const ReportsHub = lazy(() => import('@/features/reports/ReportsHubPage'))
export const SaleReport = lazy(() => import('@/features/reports/InvoiceReportPage'))
export const PurchaseReport = lazy(() => import('@/features/reports/InvoiceReportPage'))
export const PartyStatement = lazy(() => import('@/features/reports/PartyStatementPage'))
export const StockSummary = lazy(() => import('@/features/reports/StockSummaryPage'))
export const DayBook = lazy(() => import('@/features/reports/DayBookPage'))
export const PaymentHistory = lazy(() => import('@/features/reports/PaymentHistoryPage'))
export const TaxSummary = lazy(() => import('@/features/reports/TaxSummaryPage'))
export const GstReturns = lazy(() => import('@/features/reports/GstReturnsPage'))
export const TdsTcsReport = lazy(() => import('@/features/reports/TdsTcsReportPage'))
export const Settings = lazy(() => import('@/features/settings/SettingsPage'))
export const Roles = lazy(() => import('@/features/settings/RolesPage'))
export const RoleBuilder = lazy(() => import('@/features/settings/RoleBuilderPage'))
export const Staff = lazy(() => import('@/features/settings/StaffPage'))
export const StaffInvite = lazy(() => import('@/features/settings/StaffInvitePage'))
export const TransactionControls = lazy(() => import('@/features/settings/TransactionControlsPage'))
export const AuditLog = lazy(() => import('@/features/settings/AuditLogPage'))
export const ActiveSessions = lazy(() => import('@/features/settings/ActiveSessionsPage'))
export const PinSetup = lazy(() => import('@/features/settings/PinSetupPage'))
export const Shortcuts = lazy(() => import('@/features/settings/ShortcutsPage'))
export const GstSettings = lazy(() => import('@/features/tax/GstSettingsPage'))
export const TaxCategories = lazy(() => import('@/features/tax/TaxCategoriesPage'))
export const CreateTaxCategory = lazy(() => import('@/features/tax/CreateTaxCategoryPage'))
export const EditTaxCategory = lazy(() => import('@/features/tax/EditTaxCategoryPage'))
export const CurrencySettings = lazy(() => import('@/features/settings/currency/CurrencySettingsPage'))
export const RecurringList = lazy(() => import('@/features/recurring/RecurringListPage'))
export const GstReconciliationList = lazy(() => import('@/features/gst-reconciliation/ReconciliationListPage'))
export const GstReconciliationDetail = lazy(() => import('@/features/gst-reconciliation/ReconciliationDetailPage'))
export const ChartOfAccounts = lazy(() => import('@/features/accounting/ChartOfAccountsPage'))
export const JournalEntries = lazy(() => import('@/features/accounting/JournalEntriesPage'))
export const TrialBalance = lazy(() => import('@/features/accounting/TrialBalancePage'))
export const BankAccounts = lazy(() => import('@/features/bank-accounts/BankAccountsPage'))
export const Expenses = lazy(() => import('@/features/expenses/ExpensesPage'))
export const OtherIncome = lazy(() => import('@/features/other-income/OtherIncomePage'))
export const Cheques = lazy(() => import('@/features/cheques/ChequesPage'))
export const Loans = lazy(() => import('@/features/loans/LoansPage'))
export const LoanDetail = lazy(() => import('@/features/loans/LoanDetailPage'))
export const ProfitLoss = lazy(() => import('@/features/reports/ProfitLossPage'))
export const BalanceSheet = lazy(() => import('@/features/reports/BalanceSheetPage'))
export const CashFlow = lazy(() => import('@/features/reports/CashFlowPage'))
export const AgingReport = lazy(() => import('@/features/reports/AgingReportPage'))
export const ProfitabilityReport = lazy(() => import('@/features/reports/ProfitabilityReportPage'))
export const DiscountReport = lazy(() => import('@/features/reports/DiscountReportPage'))
export const TallyExport = lazy(() => import('@/features/reports/TallyExportPage'))
export const FYClosure = lazy(() => import('@/features/accounting/FYClosurePage'))
export const More = lazy(() => import('@/features/more/MorePage'))
export const BillScan = lazy(() => import('@/features/bill-scan/BillScanPage'))
export const BulkImport = lazy(() => import('@/features/bulk-import/BulkImportPage'))
export const PublicLedger = lazy(() => import('@/features/shared-ledger/PublicLedgerPage'))
export const ItemsLibrary = lazy(() => import('@/features/items-library/ItemsLibraryPage'))
export const DataImport = lazy(() => import('@/features/data-import/DataImportPage'))
export const SmartGreetings = lazy(() => import('@/features/smart-greetings/SmartGreetingsPage'))
export const Units = lazy(() => import('@/features/units/UnitsPage'))
export const JoinBusiness = lazy(() => import('@/features/business/JoinBusinessPage'))
export const CreateBusiness = lazy(() => import('@/features/business/CreateBusinessPage'))
export const Landing = lazy(() => import('@/features/landing/LandingPage'))
export const AdminCoupons = lazy(() => import('@/features/admin/coupons/CouponsPage'))
export const AdminCouponDetail = lazy(() => import('@/features/admin/coupons/CouponDetailPage'))

// Phase 4 — Advanced Inventory
export const Batches = lazy(() => import('@/features/batches/BatchesPage'))
export const CreateBatch = lazy(() => import('@/features/batches/CreateBatchPage'))
export const BatchDetail = lazy(() => import('@/features/batches/BatchDetailPage'))
export const Godowns = lazy(() => import('@/features/godowns/GodownsPage'))
export const CreateGodown = lazy(() => import('@/features/godowns/CreateGodownPage'))
export const EditGodown = lazy(() => import('@/features/godowns/EditGodownPage'))
export const GodownDetail = lazy(() => import('@/features/godowns/GodownDetailPage'))
export const GodownTransfer = lazy(() => import('@/features/godowns/TransferPage'))
export const StockVerifications = lazy(() => import('@/features/stock-verification/VerificationsPage'))
export const VerificationDetail = lazy(() => import('@/features/stock-verification/VerificationDetailPage'))
export const Serials = lazy(() => import('@/features/serial-numbers/SerialsPage'))
export const CreateSerial = lazy(() => import('@/features/serial-numbers/CreateSerialPage'))
export const BulkCreateSerial = lazy(() => import('@/features/serial-numbers/BulkCreateSerialPage'))
export const SerialLookup = lazy(() => import('@/features/serial-numbers/SerialLookupPage'))
export const Pos = lazy(() => import('@/features/pos/PosPage'))

export const StaffPermissions = lazy(() => import('@/features/settings/StaffPermissionsPage'))

export const NotFound = lazy(() => import('@/components/feedback/NotFoundPage'))
