-- Add APPOINTMENT_UPCOMING value to ReminderRuleTrigger enum (V2 Appointments Phase 1C).
-- Append-only, irreversible (Postgres cannot DROP an enum value without a type
-- rebuild). Safe: no existing rows reference it.
-- Hand-authored (not generated by `migrate dev`) because the shadow DB cannot
-- replay the historical `*_product_trgm_concurrent` migration — same workaround
-- used by 20260530152426_v2_appointments.
ALTER TYPE "ReminderRuleTrigger" ADD VALUE IF NOT EXISTS 'APPOINTMENT_UPCOMING';
