/** Payment Tracking — Constants barrel re-export
 *
 * All payment constants split into focused files.
 * Import from this file to keep existing consumer imports stable.
 */

export {
  PAYMENT_TYPE_LABELS,
  PAYMENT_TYPE_BADGE,
  PAYMENT_MODE_LABELS,
  PAYMENT_MODE_ICONS,
  REFERENCE_PLACEHOLDERS,
  MODES_WITH_REFERENCE,
  PAYMENT_DISCOUNT_TYPE_LABELS,
  PAYMENT_SORT_LABELS,
} from './payment-labels.constants'

export {
  OUTSTANDING_TYPE_LABELS,
  OUTSTANDING_SORT_LABELS,
  REMINDER_CHANNEL_LABELS,
  REMINDER_STATUS_LABELS,
  REMINDER_STATUS_BADGE,
} from './outstanding-reminder.constants'

export {
  PAYMENT_FORM_SECTION_LABELS,
  PAYMENT_DETAIL_TAB_LABELS,
  AGING_BUCKET_LABELS,
  AGING_BUCKET_COLORS,
} from './payment-ui.constants'

export {
  MAX_PAYMENT_AMOUNT,
  MIN_PAYMENT_AMOUNT,
  MAX_ALLOCATIONS_PER_PAYMENT,
  MAX_BULK_REMINDERS,
  MAX_REMINDER_RETRIES,
  MAX_REFERENCE_LENGTH,
  MAX_NOTES_LENGTH,
  MAX_DISCOUNT_REASON_LENGTH,
  MAX_REMINDER_TEMPLATE_LENGTH,
  PAYMENT_LIST_DEFAULT_LIMIT,
  PAYMENT_LIST_MAX_LIMIT,
  RECYCLE_BIN_RETENTION_DAYS,
  DEFAULT_PAYMENT_FILTERS,
  DEFAULT_OUTSTANDING_FILTERS,
  DEFAULT_REMINDER_CONFIG,
  REMINDER_TEMPLATE_VARIABLES,
} from './payment-validation.constants'
